# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:8080/person
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});

client.test("Response content-type is json", function() {
  let type = response.contentType.mimeType;
  client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
});
%}

###

POST http://localhost:8080/person
Content-Type: application/json

{"name": "Marco Amador 3"}

###

POST http://localhost:8080/api/message
Content-Type: text/plain

"test message 12345"

###

GET http://localhost:9200/_cat/indices/

###

GET http://localhost:9200/_cat/indices/blog

###

POST localhost:9200/blog/_doc/
Content-Type: application/json

{
    "name" : "John",
    "lastname" : "Doe",
    "job_description" : "Systems administrator and Linux specialist"
}

###

GET localhost:9200/blog/

###

GET http://localhost:9200/blog/_doc/TRRY75ABFZ3j7Xp5wyOL

###

GET http://localhost:9200/blog/_search

###

GET http://localhost:9200/_cluster/health

###

GET http://localhost:9200/

###
